spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username: root
    password: 217024
    url: jdbc:mysql://192.168.17.14:3306/data_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  redis:
    host: 192.168.17.14
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 1ms
        min-idle: 0
  cloud:
    stream:
      rocketmq:
        binder:
          enable-msg-trace: true
          name-server: 192.168.17.14:9876
      bindings:
        output:
          destination: test-rocketmq
          content-type: application/json
          group: product-group
        input:
          destination: test-rocketmq
          contype-type: application/json
          group: consumer-group
  elasticsearch:
    rest:
      uris: 192.168.17.14:9200
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: spring.spring.dao.entity