spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 217024
    url: jdbc:mysql://192.168.17.14:3306/data?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    name: datasource
  redis:
    host: 192.168.17.14
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  cloud:
    stream:
      default-binder: rocketmq
      rocketmq:
        binder:
          name-server: 192.168.17.14:9876
          enable-msg-trace: true
        bindings:
          input:
            consumer:
              tags: tagA || tagB
      bindings:
        output:
          binder: rocketmq
          destination: test-rocketmq
          content-type: application/json
        input:
          binder: rocketmq
          destination: test-rocketmq
          content-type: application/json
          group: rocketmq-consumer-group
  elasticsearch:
    rest:
      uris: 192.168.17.14:9200
  kafka:
    bootstrap-servers: 192.168.17.14:9092
    producer:
      batch-size: 100
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: 192.168.17.14:9092
    consumer:
      auto-commit-interval: 10s
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
  security:
    user:
      name: user
      password: user
  mvc:
    servlet:
      load-on-startup: 100
mybatis-plus:
  configuration:
    database-id: datasource
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: spring.spring.dao.entity
  global-config:
    db-config:
      id-type: auto