spring:
  datasource:
    driver-class-name: com.alibaba.druid.proxy.DruidDriver
    username: root
    password: 217024
    url: jdbc:mysql://192.168.17.14:3306/data_center?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 192.168.17.14:9876
      bindings:
        output:
          destination: test-kafka
          content-type: application/json
        input:
          destination: test-kafka
          content-type: application/json
          group: kafka-consumer-group
      default-binder: kafka